name: k6 Performance Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install k6
        run: |
          sudo apt update
          sudo apt install -y gnupg software-properties-common ca-certificates curl
          curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list > /dev/null
          sudo apt update
          sudo apt install -y k6

      - name: Run k6 Tests
        run: |
          k6 run scripts/main-test.js --out json=k6-results.json
          k6 run scripts/bdd.js --out json=k6-results.json

      - name: Generate HTML Report
        run: k6-to-html k6-results.json reports/html/results.html

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: k6-results
          path: k6-results.json
